[tool.poetry]
name = "xonshit"
version = "0.1.0"
description = "xonsh community environment"
authors = ["Mike Carifio <mike@carif.io>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
xonsh = "^0.8.8"

[tool.poetry.dev-dependencies]
pytest = "^4.1"
hypothesis = "^4.4"
black = "^18.9b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
